# Backend & Vsync Aman
backend = "glx";
vsync = true;
use-damage = false;

# Efek Bayangan Jendela
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;

# Aturan Transparansi Terminal (Sesuaikan dengan terminal Anda)
opacity-rule = [
  "90:class_g = 'Kitty'",
  "90:class_g = 'Alacritty'",
  "90:class_g = 'XTerm'"
];

# Efek Blur Premium Dual Kawase
blur: {
  method = "dual_kawase";
  strength = 5;
};
